run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  govet:
    enable-all: true
  revive:
    rules:
      - name: blank-imports
      - name: exported
      - name: unused-parameter
      - name: unreachable-code

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
